### ISSUE TITLE
Question on cmake options

### ISSUE THREAD

**Issue by Fabian188** [sergiud/SuiteSparse#8]
Maybe it is a good idea to explain the difference of the LGPL and GPL setting in the Readme?

I assume, with GPL more (all) modules are built than with LGPL? From the CMakeLists.txt I would guess cholmod is the difference?

What is Fortran required for? I guess w/o less is built?

What does MODIFY do?

Could you please tag the current version? Thanks a lot!

**Comment by sergiud** [comment]
I'm not seeing taking how this project should take the responsibility in explaining the difference between different licensings models. The licenses themselves provide all the information you need.

Modify is a module and as [I previously already explained](https://github.com/sergiud/SuiteSparse/issues/6#issuecomment-1304356689), the SuiteSparse documentation covers all the necessary information. The CMake support layer is not designed to replace the official documentation.

Having said that, let me close this issue because there's nothing actionable right now.
